### ISSUE TITLE
Missing comma

### ISSUE THREAD

**Issue by gummesson** [btford/weasel-words#3]
There's a missing comma after the word "obviously" (https://github.com/btford/weasel-words/blob/master/weasel.js#L16).

I'd be happy to send a pull request, but maybe that's overkill for just one character?

**Comment by btford** [comment]
PR welcome.

How does this code even work without a comma?!

**Comment by gummesson** [comment]
The latest version of `write-good` (both the CLI and API) blows up on 0.12.0 and iojs for me, but 0.9.0 worked fine. I've honestly got no idea...

**Comment by gummesson** [comment]
I've found the culprit of why the earlier tests passed (on TravisCI atleast): <https://travis-ci.org/btford/weasel-words/builds/44362808#L126>.

**Comment by btford** [comment]
Closed via 15fa72bdcc0fa0bff10636fdede6e3072df200b8.
